### ISSUE TITLE
VMSS - Add NSG

### ISSUE THREAD

**Issue by benofben** [couchbase-partners/azure-resource-manager-couchbase#1]

**Comment by benofben** [comment]
Currently supported per subnet in a vnet.  Support coupled to the VMSS is expected soon.

**Comment by benofben** [comment]
Going to add NSG to the VMs for now.

Please note that you have to update your firewall configuration to
allow connections to the following ports:
4369, 8091 to 8094, 9100 to 9105, 9998, 9999, 11209 to 11211,
11214, 11215, 18091 to 18093, and from 21100 to 21299.

**Comment by rafaelgodinho** [comment]
Some of the NSG ports are defined here https://github.com/rafaelgodinho/Couchbase-Azure-Marketplace/blob/master/network.json#L49-L212, we may just need to add the extra ports.

**Comment by benofben** [comment]
Ports seem to be covered here: https://developer.couchbase.com/documentation/server/current/install/install-ports.html

**Comment by benofben** [comment]
I've added all the ports to the NSG and am deploying it from main.  Need to add a dependson and connect it to the subnet

**Comment by benofben** [comment]
Should just be able to reuse our existing NSG.

**Comment by benofben** [comment]
This is attached to our vnet, so that's fine.
