### ISSUE TITLE
Add Tags

### ISSUE THREAD

**Issue by benofben** [couchbase-partners/azure-resource-manager-couchbase#13]
from Rafael

Step 1: Within the “parameters” section of an ISV’s primary solution template,
Define a tag as shown below, replacing “<isvname >” with name of the ISV
Replace “<guid >” with a GUID value w/ format  “XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX”
 
"parameters": {
…
    "<isvname>Tags": {
      "type": "object",
      "defaultValue": {
        "provider": "<guid>"
      }
    },
…
  }
 
Step 2: Tag each resource within the “resources” section (and any resources within nested templates) with a tag as follows
"tags": {
         "provider": "[toUpper(parameters('< isvname >Tags').provider)]"
       }
 
e.g.
"resources": [
…
{
       "type": "Microsoft.Network/virtualNetworks",
       "name": "[variables('virtualNetworkName')]",
       "location": "[variables('location')]",
       "apiVersion": "2015-06-15",
       "tags": {
         "displayName": "ChefVirtualNetwork"
         "provider": "[toUpper(parameters('< isvname >Tags').provider)]"
       },
},
…
{
       "name": "[variables('chefbeName')]",
       "type": "Microsoft.Storage/storageAccounts",
       "location": "[resourceGroup().location]",
       "apiVersion": "2015-06-15",
       "dependsOn": [ ],
       "tags": {
         "displayName": "BEStorage"
         "provider": "[toUpper(parameters('< isvname >Tags').provider)]"
       },
       "properties": {
         "accountType": "[parameters('chefBEType')]"
       }
},
…
{
      "type": "Microsoft.Cache/Redis",
      "name": "[variables('redisCacheNameTidy')]",
      "apiVersion": "[variables('redisApiVersion')]",
      "location": "[variables('resourceGroupLocation')]",
      "properties": {
        "sku": {
          "name": "[parameters('rediscache.skuname')]",
          "family": "[parameters('rediscache.skufamily')]",
          "capacity": "[parameters('rediscache.skucapacity')]"
        },
        "enableNonSslPort": false
      },
      "dependsOn": [ "[resourceId('Microsoft.Web/sites', variables('cdWebAppNameTidy'))]" ],
      "tags": {
         "provider": "[toUpper(parameters('< isvname >Tags').provider)]"
       }
},
…
]

**Comment by benofben** [comment]
Need to confirm where this reporting is reflected and what our GUID would be.

**Comment by benofben** [comment]
Advice from Rafael is to use couchbase instead of GUID

**Comment by rafaelgodinho** [comment]
Tags were implemented using the couchbase value.
