### ISSUE TITLE
vm0 inconsistent server name

### ISSUE THREAD

**Issue by benofben** [couchbase-partners/azure-resource-manager-couchbase#15]
![image](https://cloud.githubusercontent.com/assets/8282917/24011575/619fb73a-0a38-11e7-8283-b3e9331ff192.png)

**Comment by benofben** [comment]
per support need to run an init first https://developer.couchbase.com/documentation/server/current/cli/cbcli/node-init.html

**Comment by benofben** [comment]
Running init didn't actually change it at all.

  ./couchbase-cli node-init \
  --cluster=$vm0PrivateDNS \
  --user=$adminUsername \
  --password=$adminPassword

**Comment by mattcarabine** [comment]
@benofben I notice you didn't pass an explicit hostname to the command.

You would want to do the following instead:

```
./couchbase-cli node-init 
--cluster=$vm0PrivateDNS 
--user=$adminUsername 
--password=$adminPassword
--node-init-hostname=$vm0PrivateDNS
```

I know it seems a little counter-intuitive giving the cluster the same as the hostname, but that should work. Let me know if it doesn't.

**Comment by benofben** [comment]
Ah.  I'll give it a shot.  Thanks!

**Comment by benofben** [comment]
It works!  Thanks!
