### ISSUE TITLE
Rev Test Drive to 5.0.0

### ISSUE THREAD

**Issue by benofben** [couchbase-partners/azure-resource-manager-couchbase#58]
I've rev'd the test drive template but not the instructions.  Would need to stage, etc.  Thinking we should wait for the new subscription first.

**Comment by mgroves** [comment]
If you're referring to the instructions I wrote, the main thing to update would be authentication. So it would be low effort to just update that.

**Comment by benofben** [comment]
In progress.  Call scheduled for Monday.  The work is here: https://github.com/couchbase-partners/test-drive/blob/master/README.md

**Comment by benofben** [comment]
Done.
